### ISSUE TITLE
Add Basic CSS Styling

### ISSUE THREAD

**Issue by neilsharma** [neilsharma/test-claude-ai-app#1]
We should improve the hello world page by adding some basic CSS to make it more visually appealing:

- Add a simple background color
- Center the text
- Use a nicer font
- Add some padding and margin

Suggested implementation:
```css
body {
    font-family: Arial, sans-serif;
    background-color: #f0f0f0;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    margin: 0;
}

h1 {
    color: #333;
    text-align: center;
    padding: 20px;
    background-color: white;
    border-radius: 10px;
    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
}
```
